Node Position centrality almost fixed
2 out of 3 issues listed in the May 17th meeting report seemed to be
fixed, but because of the third issue (AttributeError: partially
initialized module 'consts' has no attribute 'CSV_FOLDER' (most likely
due to a circular import)), I can't test my code with the rest of the
program yet.

Modified file :
	src/descriptors/centrality/node_effect_centrality.py